server.port: 8302

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/jjug2017?useSSL=false
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver

doma:
  dialect: MYSQL
